Dark mode toggle
WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P3-Origins-Digital pull request #35
Opened 2024-06-13 17:19 UTC by Jxxxxj

2024-06-13 18:10 UTC, Moonlow31 approved these changes

2024-06-13 18:13 UTC, Moonlow31 requested changes
Tu as du code en commentaire

2024-06-13 20:06 UTC, Jxxxxj commented
C'est bon

2024-06-14 07:11 UTC, Moonlow31 approved these changes

2024-06-14 07:15 UTC, AurelienChetot approved these changes
Ok pour moi 👌

2024-06-14 07:16 UTC, merged